language: java
jdk:
  - oraclejdk8
  
env:
  - IDEA_VERSION=IC-2016.3.2 GRAMMAR_KIT_VERSION=1.4.3
  - IDEA_VERSION=IC-2017.1.1 GRAMMAR_KIT_VERSION=2017.1.2
  - IDEA_VERSION=IC-2017.2.3 GRAMMAR_KIT_VERSION=2017.1.2
  - IDEA_VERSION=IC-2017.3.5 GRAMMAR_KIT_VERSION=2017.1.2
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT GRAMMAR_KIT_VERSION=2017.1.2

script:
  - gradle check verifyPlugin
  
after_success:
  - gradle jacocoTestReport coveralls
